server-host: localhost
server-port: 11891
run-as-server: true
server-name: random

ui:
  header: "<bold><color:#5EFFFF>▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰<color:#00FF9B> [ 跨服银行 ] </color>▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰▰</color></bold>"
  content: "<color:#5EFFFF>⦿ <color:#00FF9B>{server}</color>  余额: <color:#FFD700>{amount}</color><newline><color:#5EFFFF>├─ </color>{action}</color>"
  footer: "<color:#5EFFFF>提示: 点击按钮操作，悬停查看说明</color>"
  action-in-server: "<green>你所在服务器</green>"
  action-unavailable: "<red>服务器不可用</red>"
  action-available: "{withdrawButton} | {depositButton}"
  loading-data: "<color:#5EFFFF>正在获取数据, 请稍后再试(1min)</color>"
  withdraw-button: "<green>取款 <click:run_command:'/cbank withdrawEx {server}'><hover:show_text:'<color:#5EFFFF>点击 <green>取款</green><newline>目标服务器: <color:#00FF9B>{server}</color><newline>在聊天栏输入金额</color>'>[↓]</hover></click></green>"
  deposit-button: "<red>存款 <click:run_command:'/cbank depositEx {server}'><hover:show_text:'<color:#5EFFFF>点击 <red>存款</red><newline>目标服务器: <color:#00FF9B>{server}</color><newline>在聊天栏输入金额</color>'>[↑]</hover></click></red>"