name: CrossBank
version: '1.0-SNAPSHOT'
main: cn.JvavRE.crossBank.CrossBank
api-version: '1.21'
author: Jvav_Runtime_Environment
description: 跨服银行插件
support-folia: true
depend:
  - Vault
commands:
  cbank:
    description: CrossBank main command
    usage: /cbank ...
permissions:
  cbank.ping:
    default: op
  cbank.reload:
    default: op
  cbank.openUI:
    default: true
  cbank.transmit:
    default: true